const translations = {
  ja: {
    pageTitle: "ウチの備瀬カフェ | 沖縄・備瀬フクギ並木のテイクアウトカフェ",
    metaDescription: "沖縄・備瀬のフクギ並木に佇む小さなテイクアウトカフェ。マンゴー×マンゴーや備瀬レモネードなど、南国ドリンクを片手にひと休み。",
    navMenu: "Menu",
    navAccess: "Access",
    heroEyebrow: "Okinawa Bise Fukugi Tree Road",
    heroTitleA: "ウチの備瀬",
    heroTitleB: "カフェ",
    heroLead: "海とフクギのあいだで、ひと休み。備瀬散策に寄り添う、小さなテイクアウトカフェです。",
    heroMenu: "メニューを見る",
    heroInstagram: "Instagramを見る",
    storyBadge: "Instagram Stories",
    storyTitle: "お得情報を毎日配信中",
    storyText: "フォローして、当日のキャンペーンや営業情報をチェック。",
    storyCta: "フォローする",
    openDate: "2026年6月3日 OPEN",
    noticeText: "営業時間・臨時休み・キャンペーンはInstagramでお知らせしています。",
    introTitle: "並木散策のあとに、冷たい一杯を。",
    introText: "備瀬のフクギ並木を歩いたあと、海へ向かう風を感じながら楽しめる南国ドリンクをご用意しています。マンゴー×マンゴーの濃厚な味わい、備瀬レモネードの爽やかさ、ウチカフェアイスコーヒーの香りまで。テイクアウトで、備瀬の時間をゆっくりどうぞ。",
    featureMangoTitle: "マンゴー×マンゴー",
    featureMangoText: "濃厚マンゴーをたっぷり使った、とろけるご褒美ドリンクです。",
    featureLatteTitle: "ウチカフェラテ",
    featureLatteText: "やさしい甘さのカフェラテ。ミルクのまろやかさがうれしい一杯です。",
    featureLemonTitle: "備瀬レモネード",
    featureLemonText: "備瀬の太陽をたっぷり浴びた、すっきりリフレッシュできるドリンクです。",
    menuTitle: "メニュー",
    menuLead: "季節や仕入れにより内容が変わる場合があります。最新の内容は店頭またはInstagramでご確認ください。",
    menuCaption: "表示言語に合わせてメニュー表も切り替わります。",
    menuListTitle: "ドリンクメニュー",
    drink1: "マンゴー×マンゴー",
    drink2: "ウチカフェラテ",
    drink3: "ウチカフェアイスコーヒー",
    drink4: "備瀬レモネード",
    drink5: "大人のベリーベリージュース",
    drink6: "ミルキーマンゴー",
    drink7: "ミルキーストロベリー",
    drink8: "ウチカフェコーヒーモヒート",
    instagramTitle: "ストーリーで、お得情報を毎日配信中。",
    instagramText: "当日の営業情報、フォロー特典、備瀬散策の小さなお知らせをInstagramで更新しています。来店前にフォローしておくと、旅の予定が少し立てやすくなります。",
    instagramCta: "Instagramをフォロー",
    instagramHandle: "@uchi_no_bise_cafe",
    instagramStory: "Stories updated daily",
    accessTitle: "店舗情報",
    accessShopLabel: "店名",
    accessShopValue: "ウチの備瀬カフェ",
    accessAreaLabel: "場所",
    accessAreaValue: "沖縄県本部町・備瀬フクギ並木エリア",
    accessHoursLabel: "営業",
    accessHoursValue: "営業日・営業時間はInstagramで最新情報をご確認ください",
    accessStyleLabel: "形式",
    accessStyleValue: "テイクアウトカフェ",
    mapCta: "Google マップで探す",
    accessAside: "Instagramフォローで特典キャンペーンを実施する場合があります。実施状況は店頭掲示またはInstagramをご確認ください。",
    menuImage: "assets/menu-ja.png",
    menuAlt: "ウチの備瀬カフェの日本語メニュー表"
  },
  en: {
    pageTitle: "Uchi no Bise Cafe | Takeout cafe in Bise, Okinawa",
    metaDescription: "A small takeout cafe by Bise Fukugi Tree Road in Okinawa. Enjoy tropical drinks such as Mango x Mango and Bise Lemonade.",
    navMenu: "Menu",
    navAccess: "Access",
    heroEyebrow: "Okinawa Bise Fukugi Tree Road",
    heroTitleA: "Uchi no",
    heroTitleB: "Bise Cafe",
    heroLead: "Take a cool break between the sea and the Fukugi trees. A small takeout cafe for your Bise stroll.",
    heroMenu: "View menu",
    heroInstagram: "Open Instagram",
    storyBadge: "Instagram Stories",
    storyTitle: "Daily deals and updates",
    storyText: "Follow us for today's offers, opening updates, and campaign news.",
    storyCta: "Follow us",
    openDate: "OPENED June 3, 2026",
    noticeText: "Opening hours, temporary closures, and campaigns are announced on Instagram.",
    introTitle: "A refreshing drink after the Fukugi walk.",
    introText: "After walking through Bise Fukugi Tree Road, enjoy tropical drinks with the sea breeze nearby. From rich Mango x Mango to refreshing Bise Lemonade and Uchi Cafe Iced Coffee, take a little Okinawan time with you.",
    featureMangoTitle: "Mango x Mango",
    featureMangoText: "A rich, rewarding drink made with plenty of ripe mango.",
    featureLatteTitle: "Uchi Cafe Latte",
    featureLatteText: "A gentle, mildly sweet cafe latte with creamy milk.",
    featureLemonTitle: "Bise Lemonade",
    featureLemonText: "A bright, refreshing drink inspired by the sunshine of Bise.",
    menuTitle: "Menu",
    menuLead: "Items may change depending on season and availability. Please check in store or on Instagram for the latest menu.",
    menuCaption: "The menu image changes with the selected language.",
    menuListTitle: "Drink Menu",
    drink1: "Mango x Mango",
    drink2: "Uchi Cafe Latte",
    drink3: "Uchi Cafe Iced Coffee",
    drink4: "Bise Lemonade",
    drink5: "Berry Berry Juice for Adults",
    drink6: "Milky Mango",
    drink7: "Milky Strawberry",
    drink8: "Uchi Cafe Coffee Mojito",
    instagramTitle: "Daily deals are posted in Stories.",
    instagramText: "We post today's opening updates, follower perks, and small Bise travel notes on Instagram. Follow before your visit to plan your stop more easily.",
    instagramCta: "Follow on Instagram",
    instagramHandle: "@uchi_no_bise_cafe",
    instagramStory: "Stories updated daily",
    accessTitle: "Information",
    accessShopLabel: "Name",
    accessShopValue: "Uchi no Bise Cafe",
    accessAreaLabel: "Area",
    accessAreaValue: "Bise Fukugi Tree Road area, Motobu, Okinawa",
    accessHoursLabel: "Hours",
    accessHoursValue: "Please check Instagram for the latest business days and hours.",
    accessStyleLabel: "Style",
    accessStyleValue: "Takeout cafe",
    mapCta: "Open Google Maps",
    accessAside: "Follower campaigns may be available. Please check the store sign or Instagram for current details.",
    menuImage: "assets/menu-en.png",
    menuAlt: "English menu for Uchi no Bise Cafe"
  },
  "zh-CN": {
    pageTitle: "Uchi no Bise Cafe | 冲绳备濑福木林道外带咖啡",
    metaDescription: "位于冲绳备濑福木林道的小型外带咖啡店。可享用芒果×芒果、备濑柠檬水等南国饮品。",
    navMenu: "菜单",
    navAccess: "交通",
    heroEyebrow: "冲绳备濑福木林道",
    heroTitleA: "Uchi no",
    heroTitleB: "Bise Cafe",
    heroLead: "在海风与福木绿荫之间，来一杯清凉饮品。适合备濑散步途中停留的小小外带咖啡店。",
    heroMenu: "查看菜单",
    heroInstagram: "查看 Instagram",
    storyBadge: "Instagram Stories",
    storyTitle: "每天发布优惠信息",
    storyText: "关注我们，查看当天优惠、营业信息与活动消息。",
    storyCta: "立即关注",
    openDate: "2026年6月3日 开业",
    noticeText: "营业时间、临时休息和活动信息会在 Instagram 公布。",
    introTitle: "福木林道散步后，来一杯冰爽饮品。",
    introText: "走过备濑福木林道后，伴着海风享用南国饮品。这里有浓郁的芒果×芒果、清爽的备濑柠檬水，以及香气十足的 Uchi Cafe 冰咖啡。外带一杯，慢慢感受备濑时光。",
    featureMangoTitle: "芒果×芒果",
    featureMangoText: "使用大量成熟芒果，口感浓郁的奖励系饮品。",
    featureLatteTitle: "Uchi Cafe 拿铁",
    featureLatteText: "温和甜感的咖啡拿铁，牛奶口感柔和顺滑。",
    featureLemonTitle: "备濑柠檬水",
    featureLemonText: "像备濑阳光一样清爽明亮的饮品。",
    menuTitle: "菜单",
    menuLead: "菜单内容可能因季节和进货情况调整。最新内容请在店内或 Instagram 确认。",
    menuCaption: "菜单图片会随所选语言切换。",
    menuListTitle: "饮品菜单",
    drink1: "芒果×芒果",
    drink2: "Uchi Cafe 拿铁",
    drink3: "Uchi Cafe 冰咖啡",
    drink4: "备濑柠檬水",
    drink5: "成人莓莓果汁",
    drink6: "牛奶芒果",
    drink7: "牛奶草莓",
    drink8: "Uchi Cafe 咖啡莫吉托",
    instagramTitle: "每天在 Stories 发布优惠信息。",
    instagramText: "当天营业信息、关注者优惠以及备濑散步小消息都会在 Instagram 更新。来店前关注一下，行程更安心。",
    instagramCta: "关注 Instagram",
    instagramHandle: "@uchi_no_bise_cafe",
    instagramStory: "Stories 每日更新",
    accessTitle: "店铺信息",
    accessShopLabel: "店名",
    accessShopValue: "Uchi no Bise Cafe",
    accessAreaLabel: "地点",
    accessAreaValue: "冲绳县本部町・备濑福木林道区域",
    accessHoursLabel: "营业",
    accessHoursValue: "营业日与时间请查看 Instagram 最新信息。",
    accessStyleLabel: "形式",
    accessStyleValue: "外带咖啡店",
    mapCta: "打开 Google 地图",
    accessAside: "可能会举办 Instagram 关注优惠活动。详情请查看店内公告或 Instagram。",
    menuImage: "assets/menu-zh-cn.png",
    menuAlt: "Uchi no Bise Cafe 简体中文菜单"
  },
  "zh-TW": {
    pageTitle: "Uchi no Bise Cafe | 沖繩備瀨福木林道外帶咖啡",
    metaDescription: "位於沖繩備瀨福木林道的小型外帶咖啡店。可享用芒果×芒果、備瀨檸檬水等南國飲品。",
    navMenu: "菜單",
    navAccess: "交通",
    heroEyebrow: "沖繩備瀨福木林道",
    heroTitleA: "Uchi no",
    heroTitleB: "Bise Cafe",
    heroLead: "在海風與福木綠蔭之間，來一杯清涼飲品。適合備瀨散步途中停留的小小外帶咖啡店。",
    heroMenu: "查看菜單",
    heroInstagram: "查看 Instagram",
    storyBadge: "Instagram Stories",
    storyTitle: "每天發布優惠資訊",
    storyText: "追蹤我們，查看當天優惠、營業資訊與活動消息。",
    storyCta: "立即追蹤",
    openDate: "2026年6月3日 開幕",
    noticeText: "營業時間、臨時休息與活動資訊會在 Instagram 公布。",
    introTitle: "福木林道散步後，來一杯冰爽飲品。",
    introText: "走過備瀨福木林道後，伴著海風享用南國飲品。這裡有濃郁的芒果×芒果、清爽的備瀨檸檬水，以及香氣十足的 Uchi Cafe 冰咖啡。外帶一杯，慢慢感受備瀨時光。",
    featureMangoTitle: "芒果×芒果",
    featureMangoText: "使用大量成熟芒果，口感濃郁的獎勵系飲品。",
    featureLatteTitle: "Uchi Cafe 拿鐵",
    featureLatteText: "溫和甜感的咖啡拿鐵，牛奶口感柔和順滑。",
    featureLemonTitle: "備瀨檸檬水",
    featureLemonText: "像備瀨陽光一樣清爽明亮的飲品。",
    menuTitle: "菜單",
    menuLead: "菜單內容可能因季節與進貨情況調整。最新內容請在店內或 Instagram 確認。",
    menuCaption: "菜單圖片會隨所選語言切換。",
    menuListTitle: "飲品菜單",
    drink1: "芒果×芒果",
    drink2: "Uchi Cafe 拿鐵",
    drink3: "Uchi Cafe 冰咖啡",
    drink4: "備瀨檸檬水",
    drink5: "成人莓莓果汁",
    drink6: "牛奶芒果",
    drink7: "牛奶草莓",
    drink8: "Uchi Cafe 咖啡莫吉托",
    instagramTitle: "每天在 Stories 發布優惠資訊。",
    instagramText: "當天營業資訊、追蹤者優惠以及備瀨散步小消息都會在 Instagram 更新。來店前先追蹤，行程更安心。",
    instagramCta: "追蹤 Instagram",
    instagramHandle: "@uchi_no_bise_cafe",
    instagramStory: "Stories 每日更新",
    accessTitle: "店鋪資訊",
    accessShopLabel: "店名",
    accessShopValue: "Uchi no Bise Cafe",
    accessAreaLabel: "地點",
    accessAreaValue: "沖繩縣本部町・備瀨福木林道區域",
    accessHoursLabel: "營業",
    accessHoursValue: "營業日與時間請查看 Instagram 最新資訊。",
    accessStyleLabel: "形式",
    accessStyleValue: "外帶咖啡店",
    mapCta: "開啟 Google 地圖",
    accessAside: "可能會舉辦 Instagram 追蹤優惠活動。詳情請查看店內公告或 Instagram。",
    menuImage: "assets/menu-zh-tw.png",
    menuAlt: "Uchi no Bise Cafe 繁體中文菜單"
  },
  ko: {
    pageTitle: "Uchi no Bise Cafe | 오키나와 비세 후쿠기 가로수길 테이크아웃 카페",
    metaDescription: "오키나와 비세 후쿠기 가로수길에 있는 작은 테이크아웃 카페. 망고×망고, 비세 레모네이드 등 남국 음료를 즐겨보세요.",
    navMenu: "메뉴",
    navAccess: "오시는 길",
    heroEyebrow: "오키나와 비세 후쿠기 가로수길",
    heroTitleA: "Uchi no",
    heroTitleB: "Bise Cafe",
    heroLead: "바다와 후쿠기 나무 사이에서 잠시 쉬어가세요. 비세 산책에 어울리는 작은 테이크아웃 카페입니다.",
    heroMenu: "메뉴 보기",
    heroInstagram: "Instagram 보기",
    storyBadge: "Instagram Stories",
    storyTitle: "매일 할인 정보를 전해요",
    storyText: "팔로우하고 오늘의 혜택, 영업 정보, 이벤트 소식을 확인하세요.",
    storyCta: "팔로우하기",
    openDate: "2026년 6월 3일 OPEN",
    noticeText: "영업시간, 임시 휴무, 이벤트는 Instagram에서 안내합니다.",
    introTitle: "후쿠기 길 산책 후, 시원한 한 잔.",
    introText: "비세 후쿠기 가로수길을 걷고 난 뒤, 바닷바람을 느끼며 남국 음료를 즐겨보세요. 진한 망고×망고, 상큼한 비세 레모네이드, 향긋한 Uchi Cafe 아이스커피까지. 테이크아웃으로 비세의 시간을 천천히 즐기세요.",
    featureMangoTitle: "망고×망고",
    featureMangoText: "잘 익은 망고를 듬뿍 사용한 진하고 달콤한 음료입니다.",
    featureLatteTitle: "Uchi Cafe 라테",
    featureLatteText: "부드러운 단맛의 카페라테. 우유의 고소함이 기분 좋은 한 잔입니다.",
    featureLemonTitle: "비세 레모네이드",
    featureLemonText: "비세의 햇살처럼 산뜻하고 상쾌한 음료입니다.",
    menuTitle: "메뉴",
    menuLead: "계절과 재료 수급에 따라 메뉴가 변경될 수 있습니다. 최신 정보는 매장 또는 Instagram에서 확인해 주세요.",
    menuCaption: "선택한 언어에 맞춰 메뉴 이미지도 바뀝니다.",
    menuListTitle: "음료 메뉴",
    drink1: "망고×망고",
    drink2: "Uchi Cafe 라테",
    drink3: "Uchi Cafe 아이스커피",
    drink4: "비세 레모네이드",
    drink5: "어른의 베리베리 주스",
    drink6: "밀키 망고",
    drink7: "밀키 스트로베리",
    drink8: "Uchi Cafe 커피 모히토",
    instagramTitle: "스토리에서 매일 할인 정보를 전해요.",
    instagramText: "오늘의 영업 정보, 팔로워 혜택, 비세 산책 소식을 Instagram에서 업데이트합니다. 방문 전 팔로우하면 여행 계획이 더 편해집니다.",
    instagramCta: "Instagram 팔로우",
    instagramHandle: "@uchi_no_bise_cafe",
    instagramStory: "Stories updated daily",
    accessTitle: "매장 정보",
    accessShopLabel: "이름",
    accessShopValue: "Uchi no Bise Cafe",
    accessAreaLabel: "위치",
    accessAreaValue: "오키나와현 모토부초 비세 후쿠기 가로수길 지역",
    accessHoursLabel: "영업",
    accessHoursValue: "영업일과 시간은 Instagram 최신 정보를 확인해 주세요.",
    accessStyleLabel: "형태",
    accessStyleValue: "테이크아웃 카페",
    mapCta: "Google 지도 열기",
    accessAside: "Instagram 팔로워 혜택 이벤트가 진행될 수 있습니다. 자세한 내용은 매장 안내 또는 Instagram을 확인해 주세요.",
    menuImage: "assets/menu-ko.png",
    menuAlt: "Uchi no Bise Cafe 한국어 메뉴"
  }
};

const languageNames = {
  ja: "日本語",
  en: "English",
  "zh-CN": "简体中文",
  "zh-TW": "繁體中文",
  ko: "한국어"
};

function applyLanguage(lang) {
  const selected = translations[lang] ? lang : "ja";
  const dictionary = translations[selected];

  document.documentElement.lang = selected;
  document.title = dictionary.pageTitle;
  document.querySelector('meta[name="description"]').setAttribute("content", dictionary.metaDescription);

  document.querySelectorAll("[data-i18n]").forEach((node) => {
    const key = node.dataset.i18n;
    if (dictionary[key]) node.textContent = dictionary[key];
  });

  const menuImage = document.querySelector("[data-menu-image]");
  if (menuImage) {
    menuImage.src = dictionary.menuImage;
    menuImage.alt = dictionary.menuAlt;
  }

  document.querySelectorAll("[data-lang]").forEach((button) => {
    const isActive = button.dataset.lang === selected;
    button.setAttribute("aria-pressed", String(isActive));
    button.title = languageNames[button.dataset.lang];
  });

  localStorage.setItem("uchiBiseLanguage", selected);
}

document.querySelectorAll("[data-lang]").forEach((button) => {
  button.addEventListener("click", () => applyLanguage(button.dataset.lang));
});

const savedLanguage = localStorage.getItem("uchiBiseLanguage");
const browserLanguage = navigator.language || "ja";
const initialLanguage = savedLanguage || (browserLanguage.startsWith("ko") ? "ko" : browserLanguage.startsWith("zh-TW") || browserLanguage.startsWith("zh-HK") ? "zh-TW" : browserLanguage.startsWith("zh") ? "zh-CN" : browserLanguage.startsWith("en") ? "en" : "ja");

applyLanguage(initialLanguage);
